version: "1.1"
services:
  db:
    image: postgres
    environment:
     POSTGRES_PASSWORD: MasterPos1212
     POSTGRES_USER: postgres
     POSTGRES_DB: data
  app:
    image: api-version-1.1 
    ports:
    - 3000:1337
  web:
    image: web-test-1.2 
    ports:
    - 5000:4000

    environment:
    
    - API_HOST=http://app:1337/api/status














