version: "1.1"
services:
  db:
    image: postgres
    environment:
     POSTGRES_PASSWORD: MasterPos1212
     POSTGRES_USER: postgres
     POSTGRES_DB: data
  app:
    image: version-4.4  
    ports:
    - 13000:1337














