api:
  image: node:latest
  ports:
    - "5000:5000"
  volumes:
    - ./:/app/
  working_dir: /app
  command: npm start

  environment:
    - PORT=3000
    - DB="postgres://postgres:MasterPos1212@localhost/data"
